# Generated by Django 6.1.1 on 2026-09-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0103_add_user_and_membership'),
        ('schedule', '0005_alter_accesstype_color_alter_accesstype_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beamlinesupport',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='support', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
