# Generated by Django 6.1.1 on 2026-09-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0103_add_user_and_membership'),
        ('schedule', '0005_alter_accesstype_color_alter_accesstype_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamtime',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamtime', to='lims.project'),
        ),
    ]
