# Generated by Django 6.1.1 on 2026-09-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_beamtime_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstype',
            options={'verbose_name': 'Access Type', 'verbose_name_plural': 'Access Types'},
        ),
        migrations.AlterModelOptions(
            name='beamlinesupport',
            options={'verbose_name': 'Beamline Support', 'verbose_name_plural': 'Beamline Support'},
        ),
        migrations.AlterModelOptions(
            name='beamtime',
            options={'ordering': ['start'], 'verbose_name': 'Beamtime', 'verbose_name_plural': 'Beamtimes'},
        ),
        migrations.AlterModelOptions(
            name='downtime',
            options={'verbose_name': 'Downtime', 'verbose_name_plural': 'Downtimes'},
        ),
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'verbose_name': 'Email Notification', 'verbose_name_plural': 'Email Notifications'},
        ),
        migrations.AlterModelOptions(
            name='facilitymode',
            options={'verbose_name': 'Facility Mode', 'verbose_name_plural': 'Facility Modes'},
        ),
    ]
