[project]
dynamic = ["version"]
name = "basic-live"
description = "A Framework for creating beamline LIMS"
license = "MIT"
authors = [
    {name = "Kathryn Janzen",email = "kathryn.janzen@lightsource.ca"},
    {name = "Michel Fodje",email = "michel.fodje@lightsource.ca"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "Django >= 6.1.1",
    "Markdown",
    "cryptography",
    "django-colorfield",
    "django-crispy-forms",
    "django-formtools",
    "django-itemlist >= 2026.1.15",
    "django-memoize",
    "django-model-utils",
    "django-proxy",
    "django-python3-ldap",
    "djangorestframework",
    "djangorestframework-simplejwt",
    "crispy-bootstrap4",
    "geopy",
    "habanero",
    "jsonfield2",
    "ldap3",
    "msgpack",
    "numpy",
    "python-dateutil",
    "requests",
    "timezonefinder",
    "fastjsonschema",
]


[tool.poetry]
packages = [
    { include = "basiclive" },
]
version = "0.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "{base}.{revision}{distance}"
