# Generated by Django 6.1.1 on 2026-09-15 16:03

import basiclive.core.acl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0020_alter_access_id_alter_accesslist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslist',
            name='address',
            field=models.CharField(max_length=45, validators=[basiclive.core.acl.models.validate_ip_or_network]),
        ),
    ]
