# Generated by Django 6.1.1 on 2026-09-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0021_alter_accesslist_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='created',
            new_name='start_time',
        ),
    ]
