# Generated by Django 6.1.1 on 2026-09-15 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0022_rename_created_access_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='end',
            new_name='end_time',
        ),
        migrations.AlterField(
            model_name='access',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
    ]
