# Generated by Django 6.1.1 on 2026-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0023_rename_end_access_end_time_alter_access_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
    ]
