# Generated by Django 6.1.1 on 2026-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0025_access_created_access_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Finished', max_length=20),
        ),
    ]
