# Generated by Django 6.1.1 on 2026-09-15 18:59

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    # Fetch the model history dynamically using the apps registry
    Access = apps.get_model('acl', 'Access')
    db_alias = schema_editor.connection.alias

    # Get a list of all distinct values for the field
    unique_values = Access.objects.using(db_alias).values_list('name', flat=True).distinct()

    for value in unique_values:
        # Keep the first record, fetch IDs of all matching duplicates after it
        duplicate_ids = (
            Access.objects.using(db_alias)
            .filter(name=value)
            .order_by('id')  # Sort to guarantee consistency
            .values_list('id', flat=True)[1:]  # Slice syntax [1:] skips the first record
        )

        # Delete the duplicate records if any exist
        if duplicate_ids:
            Access.objects.using(db_alias).filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0026_alter_access_status'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterField(
            model_name='access',
            name='name',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
