# Generated by Django 6.1.1 on 2026-09-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0027_alter_access_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Access', 'verbose_name_plural': 'Accesses'},
        ),
        migrations.AlterModelOptions(
            name='accesslist',
            options={'verbose_name': 'Access List', 'verbose_name_plural': 'Access Lists'},
        ),
    ]
