# Generated by Django 6.1.1 on 2026-09-18 01:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import basiclive.core.notebooks.fields
import basiclive.core.notebooks.models


def seed_default_data(apps, schema_editor):
    EntryType = apps.get_model('notebooks', 'EntryType')
    for name in ['text', 'image', 'video', 'sketch', 'data', 'file']:
        EntryType.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lims', '0101_project_shipping_notes_alter_project_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('tags', basiclive.core.notebooks.fields.StringListField(blank=True, verbose_name='tags')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=basiclive.core.notebooks.models.entry_storage)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.entrytype')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'Comment'), ('highlight', 'Highlight')], default='highlight', max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('node_index', models.IntegerField(default=0)),
                ('selections', basiclive.core.notebooks.fields.StringListField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='notebooks.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.SlugField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('access', models.SmallIntegerField(choices=[(0, 'Private'), (1, 'Internal'), (2, 'Public')], default=0, verbose_name='access')),
                ('editor', models.SmallIntegerField(choices=[(0, 'Owner'), (1, 'Members'), (2, 'All')], default=0, verbose_name='editor')),
                ('members', models.ManyToManyField(blank=True, related_name='shared_notebooks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notebooks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to='lims.session')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='notebooks.notebook')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='notebooks.page'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('book', 'date'), name='unique_notebook_page_date'),
        ),
        migrations.RunPython(seed_default_data, migrations.RunPython.noop),
    ]
