# Generated by Django 6.1.1 on 2026-09-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0103_add_user_and_membership'),
        ('notebooks', '0002_simplify_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notebooks', to='lims.project'),
        ),
    ]
