# Generated by Django 6.1.1 on 2026-09-28 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_alter_notebook_project'),
        ('lims', '0103_add_user_and_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='access',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='members',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='session',
        ),
        migrations.AddField(
            model_name='annotation',
            name='_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
