# Generated by Django 6.1.1 on 2026-09-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_remove_notebook_access_remove_notebook_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='_author',
            new_name='author',
        ),
    ]
