# Generated by Django 6.1.1 on 2026-09-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_consolidate_annotation_and_entry_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'verbose_name': 'Annotation', 'verbose_name_plural': 'Annotations'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['created'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='entrytype',
            options={'verbose_name': 'Entry Type', 'verbose_name_plural': 'Entry Types'},
        ),
        migrations.AlterModelOptions(
            name='notebook',
            options={'verbose_name': 'Notebook', 'verbose_name_plural': 'Notebooks'},
        ),
    ]
