# Generated by Django 6.1.1 on 2026-09-06 05:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0095_alter_activitylog_id_alter_analysisreport_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('automounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.container')),
                ('beamline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.beamline')),
                ('selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected', to='lims.container')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
