# Generated by Django 6.1.1 on 2026-09-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0096_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='automounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.automounter'),
        ),
    ]
