# Generated by Django 6.1.1 on 2026-09-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0097_alter_config_automounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
