# Generated by Django 6.1.1 on 2026-09-09 16:11

from django.db import migrations, models


def update_request_templates(apps, schema_editor):
    RequestType = apps.get_model('lims', 'RequestType')
    db_alias = schema_editor.connection.alias

    for rt in RequestType.objects.using(db_alias).all():
        updated = False
        if rt.edit_template and rt.edit_template.startswith('requests/'):
            rt.edit_template = rt.edit_template.replace('requests/', 'lims/requests/', 1)
            updated = True
        if rt.view_template and rt.view_template.startswith('requests/'):
            rt.view_template = rt.view_template.replace('requests/', 'lims/requests/', 1)
            updated = True
        if updated:
            rt.save()


def reverse_request_templates(apps, schema_editor):
    RequestType = apps.get_model('lims', 'RequestType')
    db_alias = schema_editor.connection.alias

    for rt in RequestType.objects.using(db_alias).all():
        updated = False
        if rt.edit_template and rt.edit_template.startswith('lims/requests/'):
            rt.edit_template = rt.edit_template.replace('lims/requests/', 'requests/', 1)
            updated = True
        if rt.view_template and rt.view_template.startswith('lims/requests/'):
            rt.view_template = rt.view_template.replace('lims/requests/', 'requests/', 1)
            updated = True
        if updated:
            rt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0098_config_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='edit_template',
            field=models.CharField(default='lims/requests/base-edit.html', max_length=100),
        ),
        migrations.RunPython(update_request_templates, reverse_request_templates),
    ]
