# Generated by Django on 2026-09-09

from django.db import migrations


def update_datatype_templates(apps, schema_editor):
    DataType = apps.get_model('lims', 'DataType')
    db_alias = schema_editor.connection.alias

    for dt in DataType.objects.using(db_alias).all():
        if dt.template and 'lims/entries/data' in dt.template:
            dt.template = dt.template.replace('lims/entries/data', 'lims/data/data')
            dt.save()


def reverse_datatype_templates(apps, schema_editor):
    DataType = apps.get_model('lims', 'DataType')
    db_alias = schema_editor.connection.alias

    for dt in DataType.objects.using(db_alias).all():
        if dt.template and 'lims/data/data' in dt.template:
            dt.template = dt.template.replace('lims/data/data', 'lims/entries/data')
            dt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0099_alter_requesttype_edit_template'),
    ]

    operations = [
        migrations.RunPython(update_datatype_templates, reverse_datatype_templates),
    ]
