# Generated by Django 6.1.1 on 2026-09-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0100_update_datatype_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shipping_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Shipping Notes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carrier Account Number'),
        ),
    ]
