# Generated by Django 6.1.1 on 2026-09-26 02:21

from django.core.management import call_command
from django.db import migrations


def load_requests_fixture(apps, schema_editor):
    call_command('loaddata', 'request_types.yaml', app_label='lims')


def unload_requests_fixture(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0101_project_shipping_notes_alter_project_account_number'),
    ]

    operations = [
        migrations.RunPython(load_requests_fixture, unload_requests_fixture),
    ]
