# Generated by Django 6.1.1 on 2026-09-28 17:48

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

from basiclive.core.lims.conf import settings as lims_settings


def migrate_activity_log_user(apps, schema_editor):
    ActivityLog = apps.get_model('lims', 'ActivityLog')

    # clean old entries
    cutoff_date = timezone.now() - timedelta(weeks=lims_settings.KEEP_ACTIVITY_WEEKS)
    ActivityLog.objects.filter(created__lt=cutoff_date).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0105_remove_project_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='_user',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='activities', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(migrate_activity_log_user, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='_user',
            new_name='user',
        ),
    ]
