# Generated by Django 6.1.1 on 2026-09-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0107_user_default_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ('-created',), 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['created', '-score'], 'verbose_name': 'Analysis Report', 'verbose_name_plural': 'Analysis Reports'},
        ),
        migrations.AlterModelOptions(
            name='automounter',
            options={'verbose_name': 'Automounter', 'verbose_name_plural': 'Automounters'},
        ),
        migrations.AlterModelOptions(
            name='beamline',
            options={'verbose_name': 'Beamline', 'verbose_name_plural': 'Beamlines'},
        ),
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Courier Carrier', 'verbose_name_plural': 'Courier Carriers'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ('-modified',), 'verbose_name': 'Automounter Config', 'verbose_name_plural': 'Automounter Configs'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('kind', 'location', 'name'), 'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='containerlocation',
            options={'ordering': ('kind', 'name'), 'verbose_name': 'Container Location', 'verbose_name_plural': 'Container Locations'},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'verbose_name': 'Container Type', 'verbose_name_plural': 'Container Types'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['created'], 'verbose_name': 'Dataset', 'verbose_name_plural': 'Datasets'},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Data Type', 'verbose_name_plural': 'Data Types'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['priority'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('-staff_only', 'priority'), 'verbose_name': 'Guide', 'verbose_name_plural': 'Guides'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['priority'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={'verbose_name': 'Request Type', 'verbose_name_plural': 'Request Types'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['group__priority', 'priority', 'container__name', 'location__pk', 'name'], 'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-created',), 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='sshkey',
            options={'verbose_name': 'SSH Key', 'verbose_name_plural': 'SSH Keys'},
        ),
        migrations.AlterModelOptions(
            name='stretch',
            options={'ordering': ['-start'], 'verbose_name': 'Stretch', 'verbose_name_plural': 'Stretches'},
        ),
    ]
