# Generated by Django 6.1.1 on 2026-09-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0108_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={'verbose_name': 'Component Type', 'verbose_name_plural': 'Component Types'},
        ),
        migrations.AlterModelOptions(
            name='stretch',
            options={'ordering': ['-start'], 'verbose_name': 'Session Stretch', 'verbose_name_plural': 'Session Stretches'},
        ),
    ]
