# Generated by Django 6.1.1 on 2026-10-01 14:28

from django.db import migrations, models


def migrate_legacy_simulation_beamlines(apps, schema_editor):
    Beamline = apps.get_model('lims', 'Beamline')
    for bl in Beamline.objects.all():
        if not bl.active:
            bl.simulated = True
            bl.active = True
            bl.save(update_fields=['simulated', 'active'])


def reverse_legacy_simulation_beamlines(apps, schema_editor):
    Beamline = apps.get_model('lims', 'Beamline')
    for bl in Beamline.objects.all():
        if bl.simulated:
            bl.active = False
            bl.simulated = False
            bl.save(update_fields=['simulated', 'active'])


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0109_alter_component_options_alter_componenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamline',
            name='simulated',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether this beamline is used for testing and simulation rather than physical production.',
            ),
        ),
        migrations.AlterField(
            model_name='beamline',
            name='active',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether this beamline is operational. Unselect instead of deleting decommissioned beamlines.',
            ),
        ),
        migrations.RunPython(
            migrate_legacy_simulation_beamlines,
            reverse_code=reverse_legacy_simulation_beamlines,
        ),
    ]
