# Generated by Django 6.1.1 on 2026-10-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0110_beamline_simulated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdesignation',
            options={'verbose_name': 'Project Designation', 'verbose_name_plural': 'Project Designations'},
        ),
        migrations.AlterField(
            model_name='data',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
    ]
