# Generated by Django 6.1.1 on 2026-10-03 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0111_alter_projectdesignation_options_alter_data_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='lims.session'),
        ),
    ]
