# Generated by Django 6.1.1 on 2026-10-05 05:00


from django.core.management import call_command
from django.db import migrations


def load_countries_fixture(apps, schema_editor):
    call_command('loaddata', 'countries.yaml', app_label='lims')


def unload_countries_fixture(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0114_country_region'),
    ]

    operations = [
        migrations.RunPython(load_countries_fixture, unload_countries_fixture),
    ]
