# Generated by Django 6.1.1 on 2026-10-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0115_load_country_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='key',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='username',
        ),
    ]
