# Generated by Django 6.1.1 on 2026-10-05 19:27

from django.db import migrations


def populate_activity_user(apps, schema_editor):
    ActivityLog = apps.get_model('lims', 'ActivityLog')
    to_update = ActivityLog.objects.filter(user__isnull=True, project__pi__isnull=False)
    for activity in to_update:
        activity.user_id = activity.project.pi_id
    ActivityLog.objects.bulk_update(to_update, ['user_id'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0116_remove_project_email_remove_project_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_activity_user, reverse_code=migrations.RunPython.noop),
    ]
