# Generated by Django on 2026-10-05

import django.db.models.deletion
from django.db import migrations, models


def migrate_country_region_data(apps, schema_editor):
    Project = apps.get_model('lims', 'Project')
    Country = apps.get_model('lims', 'Country')
    Region = apps.get_model('lims', 'Region')

    countries = list(Country.objects.all())
    country_by_alpha2 = {c.alpha2.upper(): c for c in countries if c.alpha2}
    country_by_alpha3 = {c.alpha3.upper(): c for c in countries if c.alpha3}
    country_by_name = {c.name.strip().upper(): c for c in countries if c.name}

    for project in Project.objects.all():
        raw_country = (project.legacy_country or "").strip().upper()
        raw_province = (project.legacy_province or "").strip()

        matched_country = None
        if raw_country:
            matched_country = (
                country_by_alpha2.get(raw_country)
                or country_by_alpha3.get(raw_country)
                or country_by_name.get(raw_country)
            )
            if matched_country:
                project.country = matched_country

        if raw_province:
            candidate_regions = Region.objects.filter(country=matched_country) if matched_country else Region.objects.all()
            matched_region = candidate_regions.filter(code__iexact=raw_province).first()
            if not matched_region:
                matched_region = candidate_regions.filter(code__iendswith=f"-{raw_province}").first()
            if not matched_region:
                matched_region = candidate_regions.filter(name__iexact=raw_province).first()

            if matched_region:
                project.region = matched_region
                if not project.country:
                    project.country = matched_region.country

        if matched_country or raw_province:
            project.save(update_fields=['country', 'region'])


def reverse_migrate_country_region_data(apps, schema_editor):
    Project = apps.get_model('lims', 'Project')
    for project in Project.objects.all():
        if project.country:
            project.legacy_country = project.country.name
        if project.region:
            project.legacy_province = project.region.name
        project.save(update_fields=['legacy_country', 'legacy_province'])


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0118_remove_activitylog_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='country',
            new_name='legacy_country',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='province',
            new_name='legacy_province',
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='lims.country',
                verbose_name='Country',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='lims.region',
                verbose_name='State / Province / Region',
            ),
        ),
        migrations.RunPython(
            migrate_country_region_data,
            reverse_migrate_country_region_data,
        ),
        migrations.RemoveField(
            model_name='project',
            name='legacy_country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='legacy_province',
        ),
    ]
