# Generated by Django 6.1.1 on 2026-10-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0119_project_country_region_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadhistory',
            options={'ordering': ['-start'], 'verbose_name': 'Load History', 'verbose_name_plural': 'Load Histories'},
        ),
    ]
