# Generated by Django 6.1.1 on 2026-09-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_alter_areafeedback_id_alter_feedback_id_and_more'),
        ('lims', '0102_create_default_requesttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrecord',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help', to='lims.project'),
        ),
    ]
