# Generated by Django 6.1.1 on 2026-09-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0081_alter_supportrecord_project'),
        ('lims', '0103_add_user_and_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrecord',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_support_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
