# Generated by Django 6.1.1 on 2026-09-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_alter_supportrecord_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areafeedback',
            options={'verbose_name': 'Area Feedback', 'verbose_name_plural': 'Area Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='likertscale',
            options={'verbose_name': 'Likert Scale', 'verbose_name_plural': 'Likert Scales'},
        ),
        migrations.AlterModelOptions(
            name='supportarea',
            options={'verbose_name': 'Support Area', 'verbose_name_plural': 'Support Areas'},
        ),
        migrations.AlterModelOptions(
            name='supportrecord',
            options={'verbose_name': 'Support Record', 'verbose_name_plural': 'Support Records'},
        ),
    ]
