# Generated by Django 6.1.1 on 2026-10-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_alter_areafeedback_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrecord',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='crm.supportarea'),
        ),
        migrations.AddIndex(
            model_name='areafeedback',
            index=models.Index(fields=['feedback', 'area'], name='crm_areafee_feedbac_80c00c_idx'),
        ),
    ]
