# Generated by Django on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


def populate_previous_records(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SupportRecord = apps.get_model('crm', 'SupportRecord')
    partitions = SupportRecord.objects.using(db_alias).values_list('area_id', 'kind', 'beamline_id').distinct()

    for area_id, kind, beamline_id in partitions:
        records = list(
            SupportRecord.objects.using(db_alias)
            .filter(area_id=area_id, kind=kind, beamline_id=beamline_id)
            .order_by('created', 'pk')
        )
        prev_record = None
        for record in records:
            prev_id = prev_record.pk if prev_record else None
            if record.previous_id != prev_id:
                record.previous_id = prev_id
            prev_record = record
        if records:
            SupportRecord.objects.using(db_alias).bulk_update(records, ['previous'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0087_remove_supportrecord_staff_and_rename_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrecord',
            name='previous',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='next_records',
                to='crm.supportrecord',
                verbose_name='Previous Record',
            ),
        ),
        migrations.RunPython(populate_previous_records, migrations.RunPython.noop),
    ]
