# Generated by Django 6.1.1 on 2026-10-07 05:42

from django.db import migrations, models


def set_feedback_labels(apps, schema_editor):
    AreaFeedback = apps.get_model('crm', 'AreaFeedback')
    to_update = AreaFeedback.objects.all()
    for feedback in to_update:
        if feedback.rating == -2:
            feedback.label = feedback.area.scale.worst
        elif feedback.rating == -1:
            feedback.label = feedback.area.scale.worse
        elif feedback.rating == 0:
            feedback.label = feedback.area.scale.neutral
        elif feedback.rating == 1:
            feedback.label = feedback.area.scale.better
        elif feedback.rating == 2:
            feedback.label = feedback.area.scale.best
        else:
            feedback.label = "N/A"
    AreaFeedback.objects.bulk_update(to_update, ['label'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0088_supportrecord_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='areafeedback',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='likertscale',
            name='neutral',
            field=models.CharField(default='Neutral', max_length=25, verbose_name='0'),
        ),
        migrations.RunPython(set_feedback_labels, reverse_code=migrations.RunPython.noop),
    ]
