# Generated by Django 6.1.1 on 2026-10-07 17:50

from django.db import migrations, models


def populate_supportarea_label(apps, schema_editor):
    SupportArea = apps.get_model('crm', 'SupportArea')
    db_alias = schema_editor.connection.alias
    areas = list(SupportArea.objects.using(db_alias).all())
    for area in areas:
        area.label = area.name
    if areas:
        SupportArea.objects.using(db_alias).bulk_update(areas, ['label'])


def reverse_populate_supportarea_label(apps, schema_editor):
    SupportArea = apps.get_model('crm', 'SupportArea')
    db_alias = schema_editor.connection.alias
    SupportArea.objects.using(db_alias).all().update(label='')


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0089_areafeedback_label_likertscale_neutral'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportarea',
            name='label',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Label'),
        ),
        migrations.RunPython(populate_supportarea_label, reverse_code=reverse_populate_supportarea_label),
    ]

