# Generated by Django 6.1.1 on 2026-09-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_alter_deposition_id_alter_funder_id_alter_journal_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='authors',
            new_name='author_names',
        ),
    ]
