# Generated by Django 6.1.1 on 2026-09-06 05:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_rename_authors_publication_author_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalprofile',
            name='expired',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(9999, 12, 2, 5, 59, 59, 999999, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='metric',
            name='expired',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(9999, 12, 2, 5, 59, 59, 999999, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
