# Generated by Django 6.1.1 on 2026-09-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_alter_journalprofile_expired_alter_metric_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposition',
            options={'verbose_name': 'Deposition', 'verbose_name_plural': 'Depositions'},
        ),
        migrations.AlterModelOptions(
            name='funder',
            options={'verbose_name': 'Funder', 'verbose_name_plural': 'Funders'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
        migrations.AlterModelOptions(
            name='journalprofile',
            options={'verbose_name': 'Journal Profile', 'verbose_name_plural': 'Journal Profiles'},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'verbose_name': 'Metric', 'verbose_name_plural': 'Metrics'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='subjectarea',
            options={'verbose_name': 'Subject Area', 'verbose_name_plural': 'Subject Areas'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveIndex(
            model_name='journalprofile',
            name='publication_owner_i_5175a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='metric',
            name='publication_owner_i_79d2eb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='journalprofile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set(),
        ),
    ]
