# Generated by Django 6.1.1 on 2026-10-08 05:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import basiclive.core.publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_alter_deposition_options_alter_funder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='metrics',
        ),
        migrations.CreateModel(
            name='ArticleMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('citations', models.IntegerField(default=0, verbose_name='Citations')),
                ('mentions', models.IntegerField(default=0, verbose_name='Mentions')),
                ('self_cites', models.IntegerField(default=0, verbose_name='Self-Citations')),
                ('year', models.IntegerField(default=basiclive.core.publications.models.default_year, verbose_name='Year')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='publications.publication')),
            ],
            options={
                'unique_together': {('publication', 'year')},
            },
        ),
        migrations.CreateModel(
            name='JournalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sjr_rank', models.FloatField(default=0.0, null=True, verbose_name='SJR-Rank')),
                ('sjr_quartile', models.SmallIntegerField(default=4, null=True, verbose_name='SJR-Quartile')),
                ('impact_factor', models.FloatField(default=0.0, null=True, verbose_name='Impact Factor')),
                ('h_index', models.IntegerField(default=1.0, null=True, verbose_name='H-Index')),
                ('year', models.IntegerField(default=basiclive.core.publications.models.default_year, verbose_name='Year')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='publications.journal')),
            ],
            options={
                'unique_together': {('journal', 'year')},
            },
        ),
    ]
