# Generated by Django 6.1.1 on 2026-10-08 05:57

from django.db import migrations


def transfer_journal_metrics(apps, schema_editor):
    """
    Transfer metrics from the old models to the new models.
    """
    JournalMetric = apps.get_model('publications', 'JournalMetric')
    JournalProfile = apps.get_model('publications', 'JournalProfile')

    # Transfer Journal metrics
    to_create = []
    for metric in JournalProfile.objects.all():
        to_create.append(
            JournalMetric(
                journal=metric.owner,
                sjr_rank=metric.sjr_rank,
                sjr_quartile=metric.sjr_quartile,
                impact_factor=metric.impact_factor,
                h_index=metric.h_index,
                year=metric.effective.year
            )
        )
    if to_create:
        JournalMetric.objects.bulk_create(to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_remove_journal_metrics_remove_publication_metrics_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_journal_metrics, reverse_code=migrations.RunPython.noop),
    ]
