# Generated by Django 6.1.1 on 2026-10-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_transfer_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemetric',
            options={'verbose_name': 'Article Metric'},
        ),
        migrations.AlterModelOptions(
            name='journalmetric',
            options={'verbose_name': 'Journal Metric'},
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
