# Generated by Django 6.1.1 on 2026-10-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_alter_articlemetric_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
