# Generated by Django 6.1.1 on 2026-10-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0021_alter_journal_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalProfile',
        ),
    ]
